#real kubernatic configration file
#pod configration
apiVersion: v1
kind: pod
metadata:
  name: nginx
  laabels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-vol
      mountPath: /usr/nginx/html

  - name: sidecar-container
    image: some-image

  - name: sidecar-container
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the side container; sleep 300"]